### ISSUE TITLE
Can't reproduce paper plots.

### ISSUE THREAD

**Issue by Datseris** [hassanalkhayuon/phaseSensitiveTipping#1]
Hi, 

I'm trying to re-create state space plots from your paper by simulating eq. (1) of your paper.

The code I have created is here: https://gist.github.com/Datseris/3a817d675dea021239fc2d822cfdc951 and used a direct copy-paste from your file here: https://github.com/hassanalkhayuon/phaseSensitiveTipping/blob/main/RM_model/BI_strip_RM.m  to create the equations of motion and obtain the parameter values.

I'm using a high precision solver (Vernier 9-th order, much more precise than Matlab's `ode45`) with high tolerances. Neither the ODE solvers of DifferentialEquations.jl (Julia), nor matplotlib's `streamplot` (Python) functions are able to reproduce what you show on the paper, e.g. Fig. 2(a).

Here is what I get instead of Fig 2(a):

![image](https://user-images.githubusercontent.com/19669089/107403072-f9cdfe00-6b04-11eb-8eb2-8a3d2cde2008.png)

The blue lines are the streamplot, the colored lines are the solutions to the ODE for various initial conditions.

Setting the y axis limits from 0 to 15, under the assumption that the 10^3 in the paper is a typo, doesn't change anything:

![image](https://user-images.githubusercontent.com/19669089/107403201-1d914400-6b05-11eb-9bc0-d71d4db51084.png)

Contrary-wise, using a standard Rozenweig-MacArthur also included in the Gist I cite above, produces normal looking plots with an obvious limit cycle as well:

![image](https://user-images.githubusercontent.com/19669089/107403377-54fff080-6b05-11eb-855d-abe441b0d7b1.png)

I'm trying to understand where we are diverging in our implementation, given that the actual equations of motion are identical and both DifferentialEquations.jl and matplotlib are extremely prestigious software and thus trustworthy.

Did I get the limits of the integration wrong? Which file of the repo is the one that creates Fig. 2(a), so I can have a closer look?

**Comment by hassanalkhayuon** [comment]
Dear Goerge,

Thank you for your interest in our work. It's much appreciated!

The 10^3 is not a typo in our paper. If I understand your code correctly, I
think you should set your y limits to be between 0 and 0.04 to get the
phase portrait in Figure 2, Please let me know if it works.

Unfortunately I don't have a clean code to produce Fig. 2 at the moment but
I'll get back to you with one very soon.

All the best,
Hassan

**Comment by Datseris** [comment]
Hi Hassan,
thank you very much for the swift reply. And your work is great, I am presenting it on my lecture tomorrow after all, as part of a larger topic on induced transitions (tipping points) in dynamical systems.

Setting my `y` limits of the simulation to 0.04 fixed the "problem":

![image](https://user-images.githubusercontent.com/19669089/107410595-cb085580-6b0d-11eb-874b-12e57364f10e.png)

Great, I now understand what Fig 2(a) was telling me. I wrongly interpreted it as the y axis being as large as 10^3, whereas I should divide it by 10^3.

I am currently working on an interactive application that reproduces the videos you made, where it will be possible to switch `r` at will while the system is evolving by pressing a button. Will share here once it is done so you can use it as well. (will be on Julia though)

**Comment by hassanalkhayuon** [comment]
Thank you George, 
I'm really glad that you're presenting this work as part of your lecture. Please do share the code for the application you're about to make. I don't use Julia, but I'm willing to learn :) 

Please feel free to contact me if you have other questions. 

All the best,
Hassan

**Comment by Datseris** [comment]
Here is the interactive code:

https://gist.github.com/Datseris/e0c7298344dd3c4e8f59e0a9772a7d93

It produces:


https://user-images.githubusercontent.com/19669089/107420603-5c30f980-6b19-11eb-96ca-e489d50fedc0.mp4

**Comment by hassanalkhayuon** [comment]
looks so cool! 

So I think you use just two values of r. the upper and lower limit, right? the actual example varies r randomly between these two values. but I think it's a good simplification to use only two. 

I'm attaching the movie I made to simulate the full example (the code in the repo I guess you already had a look at). 

https://user-images.githubusercontent.com/55986887/107498804-211bde00-6b8c-11eb-9ef3-09a941880957.mp4

All the best with you lecture :)
